version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  app:
    build:
      context: ../..
    env_file:
      - .env
    command: npm run dev
    container_name: node-app
    volumes:
      - ../../:/app
      - /app/node_modules
    expose:
      - "3000" # expose to internal Docker network only
    depends_on:
      - mongo
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../../etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge
