version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testDB
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: ../..
    command: npm run dev
    container_name: node-app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=testDB
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-data:
