name: Deployment Checks

on:
  pull_request:
    types: [edited, opened, synchronize]

jobs:
  merge-to-master-from-staging:
    name: Only Allow Merge to Master from Staging
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Check Source and Target Branches
        run: |
          if [ "${{ github.base_ref }}" != "master" ]; then
            echo "This PR is not targeting the master branch."
            exit 1
          fi
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "Merges to master are only allowed from the staging branch."
            exit 1
          fi
          echo "This PR is targeting the master branch and is from the staging branch. Merge is allowed."
