name: CI - Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      COMPOSE_PROJECT_NAME: test-stack-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Run Docker Compose (Test Stack)
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --file infra/docker/Dockerfile \
            --tag node-app-test:latest \
            --load \
            .
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          docker compose -f infra/docker/docker-compose.test.yml up -d

      - name: Run Tests inside app container
        run: |
          docker exec node-app-test npm run test:only

      - name: Shut down Docker Compose (Test Stack)
        if: always()
        run: |
          docker compose -f infra/docker/docker-compose.test.yml down -v
